In [1]:
import pandas as pd

In [2]:
# Load data dari excel
data = pd.read_excel('Data Sintetis Poin Keaktifan.xlsx')

# melihat 5 baris teratas data
data.head()

,Nama,ID_Anggota,Aktif?,Kegiatan 39 (28/03/2021),Kegiatan 38 (20/03/2021),Kegiatan 37 (19/03/2021),Kegiatan 36 (16/03/2021),Kegiatan 35 (24/02/2021),Kegiatan 34 (13/02/2021),Kegiatan 33 (27/01/2021),...,Kegiatan 9 (08/06/2020),Kegiatan 8 (26/05/2020),Kegiatan 7 (05/05/2020),Kegiatan 6 (23/04/2020),Kegiatan 5 (22/04/2020),Kegiatan 4 (20/04/2020),Kegiatan 3 (10/04/2020),Kegiatan 2 (02/04/2020),Kegiatan 1 (31/03/2020),Jumlah Poin
0,Anggota_1,A_1,Ya,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,18.0
1,Anggota_2,A_2,Ya,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,22.0
2,Anggota_3,A_3,Ya,0.0,0.0,0.0,1.0,1.0,0.0,1.0,...,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,22.0
3,Anggota_4,A_4,Tidak,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,17.0
4,Anggota_5,A_5,Ya,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,19.0

In [3]:
# melihat 5 baris terbawah data
data.tail()

,Nama,ID_Anggota,Aktif?,Kegiatan 39 (28/03/2021),Kegiatan 38 (20/03/2021),Kegiatan 37 (19/03/2021),Kegiatan 36 (16/03/2021),Kegiatan 35 (24/02/2021),Kegiatan 34 (13/02/2021),Kegiatan 33 (27/01/2021),...,Kegiatan 9 (08/06/2020),Kegiatan 8 (26/05/2020),Kegiatan 7 (05/05/2020),Kegiatan 6 (23/04/2020),Kegiatan 5 (22/04/2020),Kegiatan 4 (20/04/2020),Kegiatan 3 (10/04/2020),Kegiatan 2 (02/04/2020),Kegiatan 1 (31/03/2020),Jumlah Poin
47,Anggota_48,A_48,Tidak,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,25.0
48,Anggota_49,A_49,Tidak,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,19.0
49,Anggota_50,A_50,Ya,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,14.0
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Jumlah,NaN,NaN,27.0,28.0,26.0,22.0,20.0,26.0,29.0,...,21.0,26.0,30.0,24.0,23.0,22.0,30.0,26.0,23.0,969.0

#### Terlihat bahwa daftar anggota hanya sampai baris ke-23. Maka, baris sisanya akan dibuang.

In [4]:
# Membuang beberapa baris data terakhir yang tidak akan digunakan
data = data.iloc[:50,:]

In [5]:
# Melihat keterangan kolom
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 43 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Nama                      50 non-null     object
 1   ID_Anggota                50 non-null     object
 2   Aktif?                    50 non-null     object
 3   Kegiatan 39 (28/03/2021)  50 non-null     float64
 4   Kegiatan 38 (20/03/2021)  50 non-null     float64
 5   Kegiatan 37 (19/03/2021)  50 non-null     float64
 6   Kegiatan 36 (16/03/2021)  50 non-null     float64
 7   Kegiatan 35 (24/02/2021)  50 non-null     float64
 8   Kegiatan 34 (13/02/2021)  50 non-null     float64
 9   Kegiatan 33 (27/01/2021)  50 non-null     float64
 10  Kegiatan 32 (15/01/2021)  50 non-null     float64
 11  Kegiatan 31 (03/01/2021)  50 non-null     float64
 12  Kegiatan 30 (21/12/2020)  50 non-null     float64
 13  Kegiatan 29 (06/12/2020)  50 non-null     float64
 14  Kegiatan 28 (20/11/2020)  50 non-null     float64
 15  Kegiatan 27 (14/11/2020)  50 non-null     float64
 16  Kegiatan 26 (29/10/2020)  50 non-null     float64
 17  Kegiatan 25 (23/10/2020)  50 non-null     float64
 18  Kegiatan 24 (06/10/2020)  50 non-null     float64
 19  Kegiatan 23 (23/09/2020)  50 non-null     float64
 20  Kegiatan 22 (15/09/2020)  50 non-null     float64
 21  Kegiatan 21 (28/08/2020)  50 non-null     float64
 22  Kegiatan 20 (24/08/2020)  50 non-null     float64
 23  Kegiatan 19 (23/08/2020)  50 non-null     float64
 24  Kegiatan 18 (31/07/2020)  50 non-null     float64
 25  Kegiatan 17 (14/07/2020)  50 non-null     float64
 26  Kegiatan 16 (06/07/2020)  50 non-null     float64
 27  Kegiatan 15 (30/06/2020)  50 non-null     float64
 28  Kegiatan 14 (28/06/2020)  50 non-null     float64
 29  Kegiatan 13 (23/06/2020)  50 non-null     float64
 30  Kegiatan 12 (22/06/2020)  50 non-null     float64
 31  Kegiatan 11 (17/06/2020)  50 non-null     float64
 32  Kegiatan 10 (10/06/2020)  50 non-null     float64
 33  Kegiatan 9 (08/06/2020)   50 non-null     float64
 34  Kegiatan 8 (26/05/2020)   50 non-null     float64
 35  Kegiatan 7 (05/05/2020)   50 non-null     float64
 36  Kegiatan 6 (23/04/2020)   50 non-null     float64
 37  Kegiatan 5 (22/04/2020)   50 non-null     float64
 38  Kegiatan 4 (20/04/2020)   50 non-null     float64
 39  Kegiatan 3 (10/04/2020)   50 non-null     float64
 40  Kegiatan 2 (02/04/2020)   50 non-null     float64
 41  Kegiatan 1 (31/03/2020)   50 non-null     float64
 42  Jumlah Poin               50 non-null     float64
dtypes: float64(40), object(3)
memory usage: 16.9+ KB

In [6]:
# Mengambil anggota aktif saja
data = data[data['Aktif?']=='Ya']
data

,Nama,ID_Anggota,Aktif?,Kegiatan 39 (28/03/2021),Kegiatan 38 (20/03/2021),Kegiatan 37 (19/03/2021),Kegiatan 36 (16/03/2021),Kegiatan 35 (24/02/2021),Kegiatan 34 (13/02/2021),Kegiatan 33 (27/01/2021),...,Kegiatan 9 (08/06/2020),Kegiatan 8 (26/05/2020),Kegiatan 7 (05/05/2020),Kegiatan 6 (23/04/2020),Kegiatan 5 (22/04/2020),Kegiatan 4 (20/04/2020),Kegiatan 3 (10/04/2020),Kegiatan 2 (02/04/2020),Kegiatan 1 (31/03/2020),Jumlah Poin
0,Anggota_1,A_1,Ya,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,18.0
1,Anggota_2,A_2,Ya,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,22.0
2,Anggota_3,A_3,Ya,0.0,0.0,0.0,1.0,1.0,0.0,1.0,...,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,22.0
4,Anggota_5,A_5,Ya,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,19.0
5,Anggota_6,A_6,Ya,1.0,1.0,1.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,20.0
6,Anggota_7,A_7,Ya,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,12.0
7,Anggota_8,A_8,Ya,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,15.0
8,Anggota_9,A_9,Ya,1.0,1.0,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,18.0
9,Anggota_10,A_10,Ya,0.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,17.0
10,Anggota_11,A_11,Ya,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,16.0
11,Anggota_12,A_12,Ya,0.0,1.0,0.0,1.0,1.0,1.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,21.0
12,Anggota_13,A_13,Ya,0.0,1.0,0.0,0.0,0.0,1.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0
13,Anggota_14,A_14,Ya,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,21.0
14,Anggota_15,A_15,Ya,1.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,22.0
16,Anggota_17,A_17,Ya,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,17.0
17,Anggota_18,A_18,Ya,1.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,21.0
18,Anggota_19,A_19,Ya,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,24.0
19,Anggota_20,A_20,Ya,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,19.0
20,Anggota_21,A_21,Ya,0.0,0.0,1.0,1.0,1.0,0.0,1.0,...,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,19.0
22,Anggota_23,A_23,Ya,0.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,21.0
23,Anggota_24,A_24,Ya,0.0,1.0,1.0,1.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,24.0
24,Anggota_25,A_25,Ya,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,20.0
26,Anggota_27,A_27,Ya,1.0,0.0,1.0,0.0,1.0,1.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,20.0
27,Anggota_28,A_28,Ya,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,14.0
28,Anggota_29,A_29,Ya,1.0,0.0,1.0,0.0,0.0,1.0,1.0,...,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,18.0
29,Anggota_30,A_30,Ya,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,20.0
30,Anggota_31,A_31,Ya,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,15.0
32,Anggota_33,A_33,Ya,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,18.0
33,Anggota_34,A_34,Ya,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.0
34,Anggota_35,A_35,Ya,0.0,1.0,1.0,0.0,1.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,23.0
35,Anggota_36,A_36,Ya,0.0,1.0,1.0,0.0,1.0,1.0,0.0,...,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,25.0
36,Anggota_37,A_37,Ya,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,17.0
37,Anggota_38,A_38,Ya,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,18.0
40,Anggota_41,A_41,Ya,1.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,18.0
41,Anggota_42,A_42,Ya,1.0,0.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,23.0
42,Anggota_43,A_43,Ya,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,21.0
43,Anggota_44,A_44,Ya,0.0,1.0,1.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,21.0
44,Anggota_45,A_45,Ya,1.0,1.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,24.0
46,Anggota_47,A_47,Ya,0.0,1.0,1.0,0.0,1.0,1.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,16.0
49,Anggota_50,A_50,Ya,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,14.0

In [7]:
# Membuat Dataframe baru untuk hasil
data_hasil = data[['Nama', 'ID_Anggota', 'Jumlah Poin']]
data_hasil['Jumlah Poin'] = data_hasil['Jumlah Poin'].astype(int)
data_hasil.head()

<ipython-input-7-8db55e0fac60>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_hasil['Jumlah Poin'] = data_hasil['Jumlah Poin'].astype(int)

        Nama ID_Anggota  Jumlah Poin
0  Anggota_1        A_1           18
1  Anggota_2        A_2           22
2  Anggota_3        A_3           22
4  Anggota_5        A_5           19
5  Anggota_6        A_6           20

In [8]:
# Pilih N
N = 5

# Meyiapkan list / tempat penyimpanan sequence kegiatan anggota
list_kegiatan = []

# Looping untuk mengecek setiap anggota
for i in range(data.shape[0]):
    
    # Untuk nilai awal saja, agar bisa membuat batas maks. 3
    k = 0
    
    # Untuk menyimpan maks. 3 kegiatan anggota sebelum dimasukkan ke "list_kegiatan"
    kegiatan = []
    
    # Looping untuk mengecek kehadiran pada setiap kegiatan untuk setiap anggota 
    for j in range(3, data.shape[1]-1):
        
        # Untuk membatasi hanya 3 kegiatan, maka k < 3
        if data.iloc[i,j] == 1 and k < N:            
            kegiatan.append(data.columns[j]+'')
            k += 1
        
        # Untuk efisiensi kerja algoritma
        if k == N:
            break
    
    # Memasukkan kegiatan ke list_kegiatan
    list_kegiatan.append(', '.join(kegiatan))

data_hasil[str(N)+'-Kegiatan Terakhir yang Diikuti'] = list_kegiatan
data_hasil

<ipython-input-8-589cab00b820>:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_hasil[str(N)+'-Kegiatan Terakhir yang Diikuti'] = list_kegiatan

,Nama,ID_Anggota,Jumlah Poin,5-Kegiatan Terakhir yang Diikuti
0,Anggota_1,A_1,18,"Kegiatan 38 (20/03/2021), Kegiatan 37 (19/03/2..."
1,Anggota_2,A_2,22,"Kegiatan 38 (20/03/2021), Kegiatan 37 (19/03/2..."
2,Anggota_3,A_3,22,"Kegiatan 36 (16/03/2021), Kegiatan 35 (24/02/2..."
4,Anggota_5,A_5,19,"Kegiatan 39 (28/03/2021), Kegiatan 38 (20/03/2..."
5,Anggota_6,A_6,20,"Kegiatan 39 (28/03/2021), Kegiatan 38 (20/03/2..."
6,Anggota_7,A_7,12,"Kegiatan 38 (20/03/2021), Kegiatan 34 (13/02/2..."
7,Anggota_8,A_8,15,"Kegiatan 39 (28/03/2021), Kegiatan 37 (19/03/2..."
8,Anggota_9,A_9,18,"Kegiatan 39 (28/03/2021), Kegiatan 38 (20/03/2..."
9,Anggota_10,A_10,17,"Kegiatan 38 (20/03/2021), Kegiatan 37 (19/03/2..."
10,Anggota_11,A_11,16,"Kegiatan 39 (28/03/2021), Kegiatan 38 (20/03/2..."
11,Anggota_12,A_12,21,"Kegiatan 38 (20/03/2021), Kegiatan 36 (16/03/2..."
12,Anggota_13,A_13,19,"Kegiatan 38 (20/03/2021), Kegiatan 34 (13/02/2..."
13,Anggota_14,A_14,21,"Kegiatan 39 (28/03/2021), Kegiatan 36 (16/03/2..."
14,Anggota_15,A_15,22,"Kegiatan 39 (28/03/2021), Kegiatan 35 (24/02/2..."
16,Anggota_17,A_17,17,"Kegiatan 39 (28/03/2021), Kegiatan 38 (20/03/2..."
17,Anggota_18,A_18,21,"Kegiatan 39 (28/03/2021), Kegiatan 38 (20/03/2..."
18,Anggota_19,A_19,24,"Kegiatan 37 (19/03/2021), Kegiatan 35 (24/02/2..."
19,Anggota_20,A_20,19,"Kegiatan 39 (28/03/2021), Kegiatan 35 (24/02/2..."
20,Anggota_21,A_21,19,"Kegiatan 37 (19/03/2021), Kegiatan 36 (16/03/2..."
22,Anggota_23,A_23,21,"Kegiatan 38 (20/03/2021), Kegiatan 37 (19/03/2..."
23,Anggota_24,A_24,24,"Kegiatan 38 (20/03/2021), Kegiatan 37 (19/03/2..."
24,Anggota_25,A_25,20,"Kegiatan 38 (20/03/2021), Kegiatan 36 (16/03/2..."
26,Anggota_27,A_27,20,"Kegiatan 39 (28/03/2021), Kegiatan 37 (19/03/2..."
27,Anggota_28,A_28,14,"Kegiatan 37 (19/03/2021), Kegiatan 33 (27/01/2..."
28,Anggota_29,A_29,18,"Kegiatan 39 (28/03/2021), Kegiatan 37 (19/03/2..."
29,Anggota_30,A_30,20,"Kegiatan 39 (28/03/2021), Kegiatan 38 (20/03/2..."
30,Anggota_31,A_31,15,"Kegiatan 39 (28/03/2021), Kegiatan 38 (20/03/2..."
32,Anggota_33,A_33,18,"Kegiatan 33 (27/01/2021), Kegiatan 32 (15/01/2..."
33,Anggota_34,A_34,21,"Kegiatan 39 (28/03/2021), Kegiatan 38 (20/03/2..."
34,Anggota_35,A_35,23,"Kegiatan 38 (20/03/2021), Kegiatan 37 (19/03/2..."
35,Anggota_36,A_36,25,"Kegiatan 38 (20/03/2021), Kegiatan 37 (19/03/2..."
36,Anggota_37,A_37,17,"Kegiatan 33 (27/01/2021), Kegiatan 30 (21/12/2..."
37,Anggota_38,A_38,18,"Kegiatan 39 (28/03/2021), Kegiatan 36 (16/03/2..."
40,Anggota_41,A_41,18,"Kegiatan 39 (28/03/2021), Kegiatan 36 (16/03/2..."
41,Anggota_42,A_42,23,"Kegiatan 39 (28/03/2021), Kegiatan 36 (16/03/2..."
42,Anggota_43,A_43,21,"Kegiatan 38 (20/03/2021), Kegiatan 35 (24/02/2..."
43,Anggota_44,A_44,21,"Kegiatan 38 (20/03/2021), Kegiatan 37 (19/03/2..."
44,Anggota_45,A_45,24,"Kegiatan 39 (28/03/2021), Kegiatan 38 (20/03/2..."
46,Anggota_47,A_47,16,"Kegiatan 38 (20/03/2021), Kegiatan 37 (19/03/2..."
49,Anggota_50,A_50,14,"Kegiatan 38 (20/03/2021), Kegiatan 37 (19/03/2..."

In [9]:
data_hasil.to_excel('Hasil ' +str(N) +'-Kegiatan Anggota.xlsx', index=False)